/**
 * Completion data. Snippets use CodeMirror's #{field} syntax; a bare #{} is a tab stop.
 * Command entries: [name, argument snippet appended after \name, short description].
 */
export type CommandSpec = [name: string, args: string, detail: string];

export const TEXT_COMMANDS: CommandSpec[] = [
  ["documentclass", "{#{article}}", "Document class"],
  ["usepackage", "{#{}}", "Load a package"],
  ["title", "{#{}}", "Document title"],
  ["author", "{#{}}", "Document author"],
  ["date", "{#{\\today}}", "Document date"],
  ["maketitle", "", "Typeset the title block"],
  ["tableofcontents", "", "Table of contents"],
  ["listoffigures", "", "List of figures"],
  ["listoftables", "", "List of tables"],
  ["part", "{#{}}", "Part heading"],
  ["chapter", "{#{}}", "Chapter heading"],
  ["section", "{#{}}", "Section heading"],
  ["subsection", "{#{}}", "Subsection heading"],
  ["subsubsection", "{#{}}", "Subsubsection heading"],
  ["paragraph", "{#{}}", "Paragraph heading"],
  ["appendix", "", "Start appendices"],
  ["input", "{#{}}", "Insert a file's contents"],
  ["include", "{#{}}", "Include a file on a new page"],
  ["includeonly", "{#{}}", "Restrict \\include"],
  ["label", "{#{}}", "Label for cross-references"],
  ["ref", "{#{}}", "Reference a label"],
  ["eqref", "{#{}}", "Reference an equation"],
  ["pageref", "{#{}}", "Page of a label"],
  ["autoref", "{#{}}", "Reference with name (hyperref)"],
  ["cref", "{#{}}", "Clever reference"],
  ["Cref", "{#{}}", "Clever reference, capitalised"],
  ["nameref", "{#{}}", "Reference by title"],
  ["cite", "{#{}}", "Citation"],
  ["citep", "{#{}}", "Parenthetical citation (natbib)"],
  ["citet", "{#{}}", "Textual citation (natbib)"],
  ["parencite", "{#{}}", "Parenthetical citation (biblatex)"],
  ["textcite", "{#{}}", "Textual citation (biblatex)"],
  ["autocite", "{#{}}", "Automatic citation (biblatex)"],
  ["nocite", "{#{*}}", "Add to bibliography without citing"],
  ["bibliography", "{#{references}}", "BibTeX database"],
  ["bibliographystyle", "{#{plain}}", "BibTeX style"],
  ["addbibresource", "{#{references.bib}}", "biblatex database"],
  ["printbibliography", "", "Print biblatex bibliography"],
  ["footnote", "{#{}}", "Footnote"],
  ["footnotemark", "", "Footnote mark"],
  ["footnotetext", "{#{}}", "Footnote text"],
  ["marginpar", "{#{}}", "Margin note"],
  ["thanks", "{#{}}", "Title footnote"],
  ["today", "", "Today's date"],
  ["url", "{#{}}", "URL"],
  ["href", "{#{url}}{#{text}}", "Hyperlink"],
  ["caption", "{#{}}", "Caption"],
  ["centering", "", "Center content"],
  ["includegraphics", "[width=#{0.8}\\linewidth]{#{}}", "Insert an image"],
  ["graphicspath", "{{#{images/}}}", "Image search folders"],
  ["textbf", "{#{}}", "Bold"],
  ["textit", "{#{}}", "Italic"],
  ["emph", "{#{}}", "Emphasis"],
  ["underline", "{#{}}", "Underline"],
  ["texttt", "{#{}}", "Monospace"],
  ["textsf", "{#{}}", "Sans serif"],
  ["textrm", "{#{}}", "Roman"],
  ["textsc", "{#{}}", "Small caps"],
  ["textsl", "{#{}}", "Slanted"],
  ["textsuperscript", "{#{}}", "Superscript text"],
  ["textsubscript", "{#{}}", "Subscript text"],
  ["textcolor", "{#{red}}{#{}}", "Coloured text"],
  ["color", "{#{}}", "Switch colour"],
  ["colorbox", "{#{yellow}}{#{}}", "Coloured box"],
  ["fbox", "{#{}}", "Framed box"],
  ["mbox", "{#{}}", "Unbreakable box"],
  ["parbox", "{#{\\linewidth}}{#{}}", "Paragraph box"],
  ["raisebox", "{#{1ex}}{#{}}", "Raised box"],
  ["tiny", "", "Font size"],
  ["scriptsize", "", "Font size"],
  ["footnotesize", "", "Font size"],
  ["small", "", "Font size"],
  ["normalsize", "", "Font size"],
  ["large", "", "Font size"],
  ["Large", "", "Font size"],
  ["LARGE", "", "Font size"],
  ["huge", "", "Font size"],
  ["Huge", "", "Font size"],
  ["bfseries", "", "Bold (declaration)"],
  ["itshape", "", "Italic (declaration)"],
  ["ttfamily", "", "Monospace (declaration)"],
  ["sffamily", "", "Sans serif (declaration)"],
  ["normalfont", "", "Reset font"],
  ["hspace", "{#{1em}}", "Horizontal space"],
  ["vspace", "{#{1em}}", "Vertical space"],
  ["hfill", "", "Fill horizontal space"],
  ["vfill", "", "Fill vertical space"],
  ["smallskip", "", "Small vertical skip"],
  ["medskip", "", "Medium vertical skip"],
  ["bigskip", "", "Big vertical skip"],
  ["quad", "", "1em space"],
  ["qquad", "", "2em space"],
  ["noindent", "", "No paragraph indent"],
  ["newline", "", "Line break"],
  ["newpage", "", "Page break"],
  ["clearpage", "", "Page break, flush floats"],
  ["pagebreak", "", "Page break"],
  ["linebreak", "", "Line break"],
  ["item", " ", "List item"],
  ["newcommand", "{\\#{name}}[#{1}]{#{}}", "Define a command"],
  ["renewcommand", "{\\#{name}}{#{}}", "Redefine a command"],
  ["newenvironment", "{#{name}}{#{}}{#{}}", "Define an environment"],
  ["newtheorem", "{#{theorem}}{#{Theorem}}", "Define a theorem environment"],
  ["setlength", "{\\#{parindent}}{#{0pt}}", "Set a length"],
  ["setcounter", "{#{page}}{#{1}}", "Set a counter"],
  ["linewidth", "", "Line width"],
  ["textwidth", "", "Text width"],
  ["textheight", "", "Text height"],
  ["columnwidth", "", "Column width"],
  ["hline", "", "Table rule"],
  ["cline", "{#{1-2}}", "Partial table rule"],
  ["toprule", "", "Top rule (booktabs)"],
  ["midrule", "", "Middle rule (booktabs)"],
  ["bottomrule", "", "Bottom rule (booktabs)"],
  ["cmidrule", "{#{1-2}}", "Partial rule (booktabs)"],
  ["multicolumn", "{#{2}}{#{c}}{#{}}", "Span columns"],
  ["multirow", "{#{2}}{*}{#{}}", "Span rows"],
  ["LaTeX", "", "LaTeX logo"],
  ["TeX", "", "TeX logo"],
  ["ldots", "", "Ellipsis"],
  ["dots", "", "Ellipsis"],
  ["textbackslash", "", "Backslash"],
  ["verb", "|#{}|", "Inline verbatim"],
  ["lipsum", "[#{1}]", "Dummy text"],
  ["pagestyle", "{#{plain}}", "Page style"],
  ["thispagestyle", "{#{empty}}", "Style for this page"],
  ["pagenumbering", "{#{arabic}}", "Page number style"],
  ["frametitle", "{#{}}", "Frame title (beamer)"],
  ["pause", "", "Pause (beamer)"],
  ["titlepage", "", "Title page (beamer)"],
  ["usetheme", "{#{Madrid}}", "Beamer theme"],
  ["SI", "{#{}}{#{}}", "Number with unit (siunitx)"],
  ["si", "{#{}}", "Unit (siunitx)"],
  ["qty", "{#{}}{#{}}", "Quantity (siunitx)"],
  ["unit", "{#{}}", "Unit (siunitx)"],
  ["num", "{#{}}", "Number (siunitx)"],
  ["ang", "{#{}}", "Angle (siunitx)"],
  ["draw", " #{(0,0) -- (1,1)};", "TikZ draw"],
  ["node", " at (#{0,0}) {#{}};", "TikZ node"],
  ["fill", " #{(0,0) circle (1)};", "TikZ fill"],
  ["addplot", " #{coordinates {(0,0) (1,1)}};", "pgfplots plot"],
  ["foreach", " \\#{x} in {#{1,...,5}} {#{}}", "Loop (pgffor)"],
  ["tikz", "{#{}}", "Inline TikZ"],
  ["qedhere", "", "Place QED symbol here"],
  ["maketitle", "", "Typeset the title"],
];

export const MATH_COMMANDS: CommandSpec[] = [
  ["frac", "{#{}}{#{}}", "Fraction"],
  ["dfrac", "{#{}}{#{}}", "Display fraction"],
  ["tfrac", "{#{}}{#{}}", "Text fraction"],
  ["sqrt", "{#{}}", "Square root"],
  ["sum", "_{#{i=1}}^{#{n}}", "Sum"],
  ["prod", "_{#{i=1}}^{#{n}}", "Product"],
  ["int", "_{#{a}}^{#{b}}", "Integral"],
  ["iint", "", "Double integral"],
  ["iiint", "", "Triple integral"],
  ["oint", "", "Contour integral"],
  ["lim", "_{#{x \\to \\infty}}", "Limit"],
  ["limsup", "", "Limit superior"],
  ["liminf", "", "Limit inferior"],
  ["infty", "", "∞"],
  ["partial", "", "∂"],
  ["nabla", "", "∇"],
  ["cdot", "", "·"],
  ["cdots", "", "⋯"],
  ["vdots", "", "⋮"],
  ["ddots", "", "⋱"],
  ["times", "", "×"],
  ["div", "", "÷"],
  ["pm", "", "±"],
  ["mp", "", "∓"],
  ["leq", "", "≤"],
  ["geq", "", "≥"],
  ["neq", "", "≠"],
  ["approx", "", "≈"],
  ["equiv", "", "≡"],
  ["sim", "", "∼"],
  ["simeq", "", "≃"],
  ["cong", "", "≅"],
  ["propto", "", "∝"],
  ["ll", "", "≪"],
  ["gg", "", "≫"],
  ["subset", "", "⊂"],
  ["subseteq", "", "⊆"],
  ["supset", "", "⊃"],
  ["supseteq", "", "⊇"],
  ["in", "", "∈"],
  ["notin", "", "∉"],
  ["cup", "", "∪"],
  ["cap", "", "∩"],
  ["bigcup", "", "⋃"],
  ["bigcap", "", "⋂"],
  ["setminus", "", "∖"],
  ["emptyset", "", "∅"],
  ["varnothing", "", "∅"],
  ["forall", "", "∀"],
  ["exists", "", "∃"],
  ["neg", "", "¬"],
  ["land", "", "∧"],
  ["lor", "", "∨"],
  ["implies", "", "⟹"],
  ["iff", "", "⟺"],
  ["to", "", "→"],
  ["rightarrow", "", "→"],
  ["leftarrow", "", "←"],
  ["Rightarrow", "", "⇒"],
  ["Leftarrow", "", "⇐"],
  ["leftrightarrow", "", "↔"],
  ["Leftrightarrow", "", "⇔"],
  ["mapsto", "", "↦"],
  ["longrightarrow", "", "⟶"],
  ["uparrow", "", "↑"],
  ["downarrow", "", "↓"],
  ["left", "(#{} \\right)", "Sized delimiters"],
  ["right", "", "Closing sized delimiter"],
  ["langle", "", "⟨"],
  ["rangle", "", "⟩"],
  ["lfloor", "", "⌊"],
  ["rfloor", "", "⌋"],
  ["lceil", "", "⌈"],
  ["rceil", "", "⌉"],
  ["mathbb", "{#{R}}", "Blackboard bold"],
  ["mathbf", "{#{}}", "Bold math"],
  ["mathrm", "{#{}}", "Upright math"],
  ["mathcal", "{#{}}", "Calligraphic"],
  ["mathfrak", "{#{}}", "Fraktur"],
  ["mathit", "{#{}}", "Italic math"],
  ["mathsf", "{#{}}", "Sans serif math"],
  ["boldsymbol", "{#{}}", "Bold symbol"],
  ["operatorname", "{#{}}", "Operator name"],
  ["text", "{#{}}", "Text in math"],
  ["hat", "{#{}}", "Hat accent"],
  ["widehat", "{#{}}", "Wide hat"],
  ["bar", "{#{}}", "Bar accent"],
  ["overline", "{#{}}", "Overline"],
  ["vec", "{#{}}", "Vector arrow"],
  ["dot", "{#{}}", "Dot accent"],
  ["ddot", "{#{}}", "Double dot"],
  ["tilde", "{#{}}", "Tilde accent"],
  ["widetilde", "{#{}}", "Wide tilde"],
  ["overbrace", "{#{}}^{#{}}", "Overbrace"],
  ["underbrace", "{#{}}_{#{}}", "Underbrace"],
  ["binom", "{#{n}}{#{k}}", "Binomial"],
  ["pmod", "{#{}}", "(mod n)"],
  ["bmod", "", "mod"],
  ["sin", "", "sine"],
  ["cos", "", "cosine"],
  ["tan", "", "tangent"],
  ["arcsin", "", "arcsine"],
  ["arccos", "", "arccosine"],
  ["arctan", "", "arctangent"],
  ["sinh", "", "hyperbolic sine"],
  ["cosh", "", "hyperbolic cosine"],
  ["tanh", "", "hyperbolic tangent"],
  ["log", "", "logarithm"],
  ["ln", "", "natural log"],
  ["exp", "", "exponential"],
  ["max", "", "maximum"],
  ["min", "", "minimum"],
  ["sup", "", "supremum"],
  ["inf", "", "infimum"],
  ["det", "", "determinant"],
  ["dim", "", "dimension"],
  ["ker", "", "kernel"],
  ["deg", "", "degree"],
  ["gcd", "", "gcd"],
  ["arg", "", "argument"],
  ["angle", "", "∠"],
  ["triangle", "", "△"],
  ["perp", "", "⊥"],
  ["parallel", "", "∥"],
  ["circ", "", "∘"],
  ["bullet", "", "∙"],
  ["star", "", "⋆"],
  ["ast", "", "∗"],
  ["oplus", "", "⊕"],
  ["otimes", "", "⊗"],
  ["odot", "", "⊙"],
  ["dagger", "", "†"],
  ["ell", "", "ℓ"],
  ["hbar", "", "ℏ"],
  ["Re", "", "ℜ"],
  ["Im", "", "ℑ"],
  ["aleph", "", "ℵ"],
  ["prime", "", "′"],
  ["tag", "{#{}}", "Custom equation tag"],
  ["notag", "", "No equation number"],
  ["nonumber", "", "No equation number"],
  ["displaystyle", "", "Display style"],
  ["limits", "", "Limits above/below"],
  ["substack", "{#{}}", "Stacked subscript"],
  ["overset", "{#{}}{#{}}", "Symbol above"],
  ["underset", "{#{}}{#{}}", "Symbol below"],
  ["xrightarrow", "{#{}}", "Extensible arrow"],
  ["alpha", "", "α"], ["beta", "", "β"], ["gamma", "", "γ"], ["delta", "", "δ"],
  ["epsilon", "", "ϵ"], ["varepsilon", "", "ε"], ["zeta", "", "ζ"], ["eta", "", "η"],
  ["theta", "", "θ"], ["vartheta", "", "ϑ"], ["iota", "", "ι"], ["kappa", "", "κ"],
  ["lambda", "", "λ"], ["mu", "", "μ"], ["nu", "", "ν"], ["xi", "", "ξ"], ["pi", "", "π"],
  ["varpi", "", "ϖ"], ["rho", "", "ρ"], ["varrho", "", "ϱ"], ["sigma", "", "σ"],
  ["varsigma", "", "ς"], ["tau", "", "τ"], ["upsilon", "", "υ"], ["phi", "", "ϕ"],
  ["varphi", "", "φ"], ["chi", "", "χ"], ["psi", "", "ψ"], ["omega", "", "ω"],
  ["Gamma", "", "Γ"], ["Delta", "", "Δ"], ["Theta", "", "Θ"], ["Lambda", "", "Λ"],
  ["Xi", "", "Ξ"], ["Pi", "", "Π"], ["Sigma", "", "Σ"], ["Upsilon", "", "Υ"],
  ["Phi", "", "Φ"], ["Psi", "", "Ψ"], ["Omega", "", "Ω"],
];

export interface EnvSpec {
  name: string;
  body?: string;
  arg?: string;
  detail: string;
}

export const ENVIRONMENTS: EnvSpec[] = [
  { name: "document", detail: "Document body" },
  { name: "abstract", detail: "Abstract" },
  { name: "itemize", body: "\t\\item #{}", detail: "Bulleted list" },
  { name: "enumerate", body: "\t\\item #{}", detail: "Numbered list" },
  { name: "description", body: "\t\\item[#{term}] #{}", detail: "Description list" },
  { name: "equation", detail: "Numbered equation" },
  { name: "equation*", detail: "Unnumbered equation" },
  { name: "align", body: "\t#{} &= #{} \\\\", detail: "Aligned equations" },
  { name: "align*", body: "\t#{} &= #{} \\\\", detail: "Aligned equations, unnumbered" },
  { name: "gather", detail: "Centered equations" },
  { name: "gather*", detail: "Centered equations, unnumbered" },
  { name: "multline", detail: "Multi-line equation" },
  { name: "split", detail: "Split equation" },
  { name: "cases", body: "\t#{} & \\text{if } #{} \\\\\n\t#{} & \\text{otherwise}", detail: "Piecewise cases" },
  { name: "matrix", detail: "Matrix" },
  { name: "pmatrix", body: "\t#{a} & #{b} \\\\\n\t#{c} & #{d}", detail: "Matrix with ( )" },
  { name: "bmatrix", body: "\t#{a} & #{b} \\\\\n\t#{c} & #{d}", detail: "Matrix with [ ]" },
  { name: "vmatrix", detail: "Determinant" },
  { name: "array", arg: "{#{cc}}", detail: "Math array" },
  {
    name: "figure",
    arg: "[#{ht}]",
    body: "\t\\centering\n\t\\includegraphics[width=0.8\\linewidth]{#{file}}\n\t\\caption{#{caption}}\n\t\\label{fig:#{label}}",
    detail: "Figure float",
  },
  {
    name: "table",
    arg: "[#{ht}]",
    body: "\t\\centering\n\t\\begin{tabular}{#{cc}}\n\t\t#{} & #{} \\\\\n\t\\end{tabular}\n\t\\caption{#{caption}}\n\t\\label{tab:#{label}}",
    detail: "Table float",
  },
  { name: "tabular", arg: "{#{cc}}", body: "\t#{} & #{} \\\\", detail: "Table" },
  { name: "tabularx", arg: "{\\linewidth}{#{XX}}", body: "\t#{} & #{} \\\\", detail: "Full-width table" },
  { name: "longtable", arg: "{#{cc}}", detail: "Multi-page table" },
  { name: "center", detail: "Centered block" },
  { name: "flushleft", detail: "Left-aligned block" },
  { name: "flushright", detail: "Right-aligned block" },
  { name: "minipage", arg: "{#{0.48}\\textwidth}", detail: "Mini page" },
  { name: "quote", detail: "Quotation" },
  { name: "quotation", detail: "Long quotation" },
  { name: "verbatim", detail: "Verbatim text" },
  { name: "lstlisting", arg: "[language=#{Python}]", detail: "Code listing" },
  { name: "minted", arg: "{#{python}}", detail: "Highlighted code" },
  { name: "theorem", detail: "Theorem" },
  { name: "lemma", detail: "Lemma" },
  { name: "proof", detail: "Proof" },
  { name: "definition", detail: "Definition" },
  { name: "corollary", detail: "Corollary" },
  { name: "proposition", detail: "Proposition" },
  { name: "remark", detail: "Remark" },
  { name: "example", detail: "Example" },
  { name: "frame", arg: "{#{title}}", detail: "Beamer slide" },
  { name: "block", arg: "{#{title}}", detail: "Beamer block" },
  { name: "columns", body: "\t\\column{0.5\\textwidth}\n\t#{}\n\t\\column{0.5\\textwidth}\n\t#{}", detail: "Beamer columns" },
  { name: "tikzpicture", detail: "TikZ drawing" },
  { name: "axis", arg: "[xlabel={#{x}}, ylabel={#{y}}]", body: "\t\\addplot {#{x^2}};", detail: "pgfplots axis" },
  { name: "subfigure", arg: "{#{0.48}\\textwidth}", detail: "Sub-figure (subcaption)" },
  { name: "thebibliography", arg: "{#{9}}", body: "\t\\bibitem{#{key}} #{}", detail: "Manual bibliography" },
  { name: "titlepage", detail: "Title page" },
  { name: "multicols", arg: "{#{2}}", detail: "Multiple columns" },
  { name: "wrapfigure", arg: "{#{r}}{#{0.4}\\textwidth}", detail: "Text-wrapped figure" },
  { name: "algorithm", detail: "Algorithm float" },
  { name: "algorithmic", detail: "Pseudocode" },
  { name: "comment", detail: "Commented-out block" },
];

export const PACKAGES: [string, string][] = [
  ["amsmath", "Math environments"], ["amssymb", "Math symbols"], ["amsthm", "Theorems"], ["amsfonts", "Math fonts"],
  ["mathtools", "amsmath extensions"], ["graphicx", "Images"], ["xcolor", "Colours"], ["hyperref", "Links"],
  ["geometry", "Page layout"], ["babel", "Languages"], ["inputenc", "Input encoding"], ["fontenc", "Font encoding"],
  ["lmodern", "Latin Modern fonts"], ["microtype", "Micro-typography"], ["booktabs", "Table rules"],
  ["tabularx", "Full-width tables"], ["longtable", "Multi-page tables"], ["multirow", "Row spans"], ["array", "Table columns"],
  ["siunitx", "Units and numbers"], ["tikz", "Drawings"], ["pgfplots", "Plots"], ["caption", "Captions"],
  ["subcaption", "Sub-figures"], ["float", "Float placement [H]"], ["wrapfig", "Wrapped figures"], ["enumitem", "List styles"],
  ["fancyhdr", "Headers/footers"], ["titlesec", "Heading styles"], ["tocloft", "TOC styles"], ["listings", "Code listings"],
  ["minted", "Highlighted code"], ["algorithm", "Algorithm floats"], ["algpseudocode", "Pseudocode"],
  ["algorithm2e", "Algorithms"], ["cleveref", "Clever references"], ["natbib", "Citations"], ["biblatex", "Bibliographies"],
  ["csquotes", "Quotes"], ["lipsum", "Dummy text"], ["blindtext", "Dummy text"], ["setspace", "Line spacing"],
  ["parskip", "Paragraph spacing"], ["xparse", "Command definitions"], ["etoolbox", "Programming tools"],
  ["ifthen", "Conditionals"], ["calc", "Arithmetic"], ["multicol", "Columns"], ["tcolorbox", "Coloured boxes"],
  ["mdframed", "Framed boxes"], ["url", "URLs"], ["bm", "Bold math"], ["physics", "Physics notation"], ["cancel", "Cancel terms"],
  ["chemfig", "Chemical structures"], ["mhchem", "Chemical formulae"], ["circuitikz", "Circuits"], ["pdfpages", "Insert PDFs"],
  ["appendix", "Appendices"], ["glossaries", "Glossaries"], ["imakeidx", "Indexes"], ["nomencl", "Nomenclature"],
  ["acronym", "Acronyms"], ["todonotes", "Todo notes"], ["comment", "Comment blocks"], ["verbatim", "Verbatim"],
  ["fancyvrb", "Fancy verbatim"], ["xspace", "Smart spaces"], ["textcomp", "Text symbols"], ["gensymb", "Degree etc."],
  ["upgreek", "Upright Greek"], ["mathrsfs", "Script letters"], ["dsfont", "Double-struck"], ["esint", "Integrals"],
  ["nicefrac", "Nice fractions"], ["xfrac", "Split fractions"], ["fontspec", "System fonts (XeLaTeX/LuaLaTeX)"],
  ["unicode-math", "Unicode math (XeLaTeX/LuaLaTeX)"], ["polyglossia", "Languages (XeLaTeX)"], ["csvsimple", "CSV tables"],
  ["pgfplotstable", "Tables from data"], ["standalone", "Standalone figures"], ["subfiles", "Compilable sub-files"],
  ["placeins", "\\FloatBarrier"], ["rotating", "Rotation"], ["pdflscape", "Landscape pages"], ["adjustbox", "Box adjustments"],
  ["threeparttable", "Table notes"], ["makecell", "Table cells"], ["colortbl", "Coloured tables"], ["ragged2e", "Ragged text"],
  ["footmisc", "Footnote styles"], ["titling", "Title styles"], ["authblk", "Author affiliations"], ["bookmark", "PDF bookmarks"],
  ["xurl", "URL breaks"], ["tikz-cd", "Commutative diagrams"], ["forest", "Trees"], ["fontawesome5", "Icons"],
  ["marvosym", "Symbols"], ["pifont", "Dingbats"], ["svg", "SVG images (needs Inkscape)"], ["graphbox", "Image alignment"],
];

export const DOCUMENT_CLASSES: [string, string][] = [
  ["article", "Articles, short reports"], ["report", "Longer reports with chapters"], ["book", "Books"],
  ["letter", "Letters"], ["beamer", "Presentations"], ["memoir", "Flexible book class"], ["scrartcl", "KOMA article"],
  ["scrreprt", "KOMA report"], ["scrbook", "KOMA book"], ["amsart", "AMS article"], ["IEEEtran", "IEEE papers"],
  ["elsarticle", "Elsevier articles"], ["llncs", "Springer LNCS"], ["acmart", "ACM papers"], ["revtex4-2", "APS/AIP papers"],
  ["standalone", "Single figure"], ["exam", "Exams"], ["moderncv", "CVs"], ["tufte-handout", "Tufte handout"], ["minimal", "Minimal"],
];
